language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE questioner;" -U postgres
  - psql -c "CREATE USER questioneruser WITH PASSWORD 'id28294242';" -U postgres
  - python3 manage.py migrate
script:
  - pytest
  - pytest --cov-report term-missing --cov=app

after_success:
  - coveralls
